export type Product = {
  id: string
  name: string
  brand: string
  tagline: string
  description: string
  price: number
  /** Primary image — always present */
  image: string
  /** Additional gallery images; falls back to [image] if empty */
  images?: string[]
  category: string
  tag?: "Bestseller" | "New" | "Sale" | "Low Stock"
  benefits: string[]
  ingredients: string[]
  concerns: string[]
  stock: number
  rating: number
  reviewCount: number
  size?: string
  variants?: { label: string; price: number }[]
}

export const BRANDS = [
  { id: "cerave",        name: "CeraVe",          tagline: "Developed with dermatologists" },
  { id: "the-ordinary",  name: "The Ordinary",     tagline: "Clinical formulations with integrity" },
  { id: "la-roche-posay",name: "La Roche-Posay",   tagline: "Recommended by dermatologists worldwide" },
  { id: "cosrx",         name: "COSRX",            tagline: "Korean skincare essentials" },
  { id: "neutrogena",    name: "Neutrogena",        tagline: "Dermatologist recommended" },
  { id: "paulas-choice", name: "Paula's Choice",   tagline: "Ingredient-focused formulas" },
  { id: "cetaphil",      name: "Cetaphil",          tagline: "Gentle care for all skin types" },
  { id: "bioderma",      name: "Bioderma",          tagline: "Pioneering dermocosmetics" },
  { id: "vichy",         name: "Vichy",             tagline: "Volcanic mineralising water" },
  { id: "hayda",         name: "HAYDA",             tagline: "Curated by HAYDA SKINCo." },
]

export const products: Product[] = [
  {
    id: "cerave-hydrating-cleanser",
    name: "Hydrating Facial Cleanser",
    brand: "CeraVe",
    tagline: "Gentle daily cleanser for normal to dry skin",
    description: "This gentle non-foaming cleanser is formulated with three essential ceramides and hyaluronic acid to help maintain the skin's natural protective barrier while effectively removing dirt and makeup.",
    price: 5500,
    image: "/product-cleanser.png",
    images: ["/product-cleanser.png", "/product-cream.png", "/product-toner.png"],
    category: "Cleansers",
    tag: "Bestseller",
    benefits: ["Cleanses without stripping", "Maintains moisture barrier", "Non-comedogenic", "Fragrance-free"],
    ingredients: ["Ceramides", "Hyaluronic Acid", "Glycerin"],
    concerns: ["Dry Skin", "Sensitive Skin"],
    stock: 48,
    rating: 4.8,
    reviewCount: 342,
    size: "237ml",
    variants: [
      { label: "237ml", price: 5500 },
      { label: "473ml", price: 9200 },
      { label: "1L", price: 16500 },
    ],
  },
  {
    id: "ordinary-niacinamide",
    name: "Niacinamide 10% + Zinc 1%",
    brand: "The Ordinary",
    tagline: "High-strength vitamin and mineral blemish formula",
    description: "A high-strength vitamin and mineral blemish formula that visibly addresses uneven skin tone, blemishes, and enlarged pores. Contains 10% niacinamide and 1% zinc PCA.",
    price: 3800,
    image: "/product-serum.png",
    images: ["/product-serum.png", "/product-toner.png", "/product-oil.png"],
    category: "Serums",
    tag: "Bestseller",
    benefits: ["Reduces blemishes", "Minimises pore appearance", "Evens skin tone", "Regulates sebum"],
    ingredients: ["Niacinamide", "Zinc PCA"],
    concerns: ["Acne", "Oily Skin", "Hyperpigmentation"],
    stock: 65,
    rating: 4.7,
    reviewCount: 512,
    size: "30ml",
  },
  {
    id: "ordinary-vitamin-c",
    name: "Vitamin C Suspension 23% + HA 2%",
    brand: "The Ordinary",
    tagline: "Potent antioxidant brightening serum",
    description: "A potent brightening formula with 23% L-Ascorbic Acid and 2% Hyaluronic Acid Spheres to brighten the complexion and combat oxidative stress.",
    price: 3600,
    image: "/product-serum.png",
    images: ["/product-serum.png", "/product-oil.png"],
    category: "Serums",
    tag: "Sale",
    benefits: ["Brightens complexion", "Antioxidant protection", "Reduces dark spots", "Anti-ageing"],
    ingredients: ["Vitamin C", "Hyaluronic Acid"],
    concerns: ["Hyperpigmentation", "Anti-Ageing"],
    stock: 30,
    rating: 4.5,
    reviewCount: 289,
    size: "30ml",
  },
  {
    id: "lrp-toleriane-moisturiser",
    name: "Toleriane Double Repair Moisturiser",
    brand: "La Roche-Posay",
    tagline: "Prebiotic moisturiser restores skin barrier",
    description: "Formulated with a prebiotic formula and niacinamide, this moisturiser instantly hydrates and repairs the skin's natural barrier for up to 48 hours.",
    price: 12500,
    image: "/product-cream.png",
    images: ["/product-cream.png", "/product-serum.png", "/product-toner.png"],
    category: "Moisturisers",
    tag: "Bestseller",
    benefits: ["48-hour hydration", "Repairs skin barrier", "Prebiotic formula", "Fragrance-free"],
    ingredients: ["Niacinamide", "Ceramides", "Glycerin"],
    concerns: ["Dry Skin", "Sensitive Skin"],
    stock: 22,
    rating: 4.9,
    reviewCount: 198,
    size: "75ml",
  },
  {
    id: "cosrx-snail-mucin",
    name: "Advanced Snail 96 Mucin Power Essence",
    brand: "COSRX",
    tagline: "96% snail secretion filtrate essence",
    description: "This essence contains 96% Snail Secretion Filtrate to heal blemishes and boost radiance. Lightweight formula absorbs quickly, improving moisture and elasticity.",
    price: 8900,
    image: "/product-serum.png",
    images: ["/product-serum.png", "/product-toner.png"],
    category: "Serums",
    benefits: ["Heals blemishes", "Boosts radiance", "Improves elasticity", "Lightweight"],
    ingredients: ["Snail Secretion Filtrate", "Hyaluronic Acid"],
    concerns: ["Acne", "Dry Skin", "Anti-Ageing"],
    stock: 35,
    rating: 4.8,
    reviewCount: 467,
    size: "100ml",
  },
  {
    id: "paulas-bha",
    name: "Skin Perfecting 2% BHA Liquid Exfoliant",
    brand: "Paula's Choice",
    tagline: "Leave-on exfoliant for blackheads & pores",
    description: "This leave-on exfoliant with 2% salicylic acid gently unclogs and minimises enlarged pores, removes dead skin on the surface and inside the pore, and smooths the skin.",
    price: 18500,
    image: "/product-toner.png",
    images: ["/product-toner.png", "/product-serum.png", "/product-cleanser.png"],
    category: "Treatments",
    tag: "Bestseller",
    benefits: ["Unclogs pores", "Smooths skin texture", "Reduces blackheads", "Anti-inflammatory"],
    ingredients: ["AHA/BHA", "Salicylic Acid", "Methylpropanediol"],
    concerns: ["Acne", "Oily Skin"],
    stock: 18,
    rating: 4.9,
    reviewCount: 623,
    size: "118ml",
  },
  {
    id: "lrp-anthelios-spf50",
    name: "Anthelios UVMune 400 SPF 50+",
    brand: "La Roche-Posay",
    tagline: "Invisible fluid broad-spectrum SPF 50+",
    description: "Lightweight invisible fluid sun protection with Mexoryl 400 technology providing exceptional UVA protection. Suitable for sensitive skin.",
    price: 16000,
    image: "/product-cream.png",
    images: ["/product-cream.png", "/product-oil.png"],
    category: "Sunscreen",
    tag: "Bestseller",
    benefits: ["SPF 50+ protection", "UVA/UVB broad spectrum", "Lightweight invisible", "Water resistant"],
    ingredients: ["SPF", "Mexoryl 400", "Tinosorb S"],
    concerns: ["Anti-Ageing", "Sensitive Skin"],
    stock: 40,
    rating: 4.7,
    reviewCount: 334,
    size: "50ml",
  },
  {
    id: "neutrogena-retinol",
    name: "Rapid Wrinkle Repair Retinol Serum",
    brand: "Neutrogena",
    tagline: "Accelerated retinol SA for visibly smoother skin",
    description: "An accelerated retinol formula with hyaluronic acid and glycerin that visibly reduces the look of fine lines and wrinkles in just one week.",
    price: 11500,
    image: "/product-serum.png",
    images: ["/product-serum.png", "/product-oil.png", "/product-cream.png"],
    category: "Serums",
    tag: "Sale",
    benefits: ["Reduces fine lines", "Smooths texture", "Deep hydration", "Clinically proven"],
    ingredients: ["Retinol", "Hyaluronic Acid", "Glycerin"],
    concerns: ["Anti-Ageing"],
    stock: 25,
    rating: 4.5,
    reviewCount: 278,
    size: "30ml",
  },
  {
    id: "cerave-eye-repair",
    name: "Eye Repair Cream",
    brand: "CeraVe",
    tagline: "Gentle eye cream for dark circles & puffiness",
    description: "Formulated with ceramides and niacinamide to reduce the appearance of dark circles and puffiness around the delicate eye area.",
    price: 5800,
    tag: "Sale",
    image: "/product-eye.png",
    images: ["/product-eye.png", "/product-cream.png"],
    category: "Eye Care",
    benefits: ["Reduces dark circles", "Minimises puffiness", "Ceramide-rich", "Fragrance-free"],
    ingredients: ["Ceramides", "Niacinamide", "Hyaluronic Acid"],
    concerns: ["Anti-Ageing", "Dry Skin"],
    stock: 30,
    rating: 4.6,
    reviewCount: 189,
    size: "14.2g",
  },
  {
    id: "bioderma-sensibio",
    name: "Sensibio H2O Micellar Water",
    brand: "Bioderma",
    tagline: "Original micellar cleansing water for sensitive skin",
    description: "The original micellar water that gently removes makeup, cleanses, and soothes even the most sensitive skin without rinsing.",
    price: 9500,
    image: "/product-cleanser.png",
    images: ["/product-cleanser.png", "/product-toner.png", "/product-serum.png"],
    category: "Cleansers",
    tag: "Bestseller",
    benefits: ["Removes all makeup", "Soothes sensitive skin", "No rinse needed", "pH-balanced"],
    ingredients: ["Cucumber Extract", "Fructooligosaccharides"],
    concerns: ["Sensitive Skin"],
    stock: 55,
    rating: 4.8,
    reviewCount: 445,
    size: "500ml",
  },
  {
    id: "ordinary-aha-bha",
    name: "AHA 30% + BHA 2% Peeling Solution",
    brand: "The Ordinary",
    tagline: "10-minute exfoliating facial mask",
    description: "An exfoliating solution with 30% alpha hydroxy acids (AHA) and 2% beta hydroxy acid (BHA) to help visibly improve skin radiance and texture in just 10 minutes.",
    price: 4800,
    image: "/product-toner.png",
    images: ["/product-toner.png", "/product-serum.png"],
    tag: "New",
    category: "Treatments",
    benefits: ["Deep exfoliation", "Improved radiance", "Reduced texture", "Targets dark spots"],
    ingredients: ["AHA/BHA", "Glycolic Acid", "Salicylic Acid", "Vitamin C"],
    concerns: ["Hyperpigmentation", "Acne", "Anti-Ageing"],
    stock: 42,
    rating: 4.6,
    reviewCount: 512,
    size: "30ml",
  },
  {
    id: "cerave-moisturising-cream",
    name: "Moisturising Cream",
    brand: "CeraVe",
    tagline: "Rich 24-hour barrier cream for dry to very dry skin",
    description: "Rich, non-greasy cream with three essential ceramides and MVE technology for 24-hour hydration. Restores and maintains the skin's natural barrier.",
    price: 8900,
    image: "/product-cream.png",
    images: ["/product-cream.png", "/product-cleanser.png", "/product-serum.png"],
    category: "Moisturisers",
    benefits: ["24-hour hydration", "Restores skin barrier", "Non-greasy", "Suitable for face & body"],
    ingredients: ["Ceramides", "Hyaluronic Acid", "Petrolatum"],
    concerns: ["Dry Skin", "Sensitive Skin"],
    stock: 60,
    rating: 4.9,
    reviewCount: 789,
    size: "454g",
    tag: "Bestseller",
  },
]

export function getProduct(id: string) {
  return products.find(p => p.id === id)
}

export function formatPrice(price: number) {
  return new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(price)
}

export const ALL_CONCERNS = ["Acne", "Hyperpigmentation", "Anti-Ageing", "Dry Skin", "Oily Skin", "Sensitive Skin"]
export const ALL_INGREDIENTS = ["Vitamin C", "Retinol", "Niacinamide", "AHA/BHA", "Hyaluronic Acid", "SPF", "Ceramides"]
export const ALL_CATEGORIES = ["Cleansers", "Toners", "Serums", "Moisturisers", "Sunscreen", "Eye Care", "Treatments"]
